//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_OnlineDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatBoard
    {
        public int ChatBroad_Id { get; set; }
        public string Message { get; set; }
        public string FromUser { get; set; }
        public Nullable<System.DateTime> DateTimeOfMessage { get; set; }
    }
}
