//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_OnlineDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public int User_Id { get; set; }
        public string UserName { get; set; }

        [Display(Name = "PassWord")]
        public string PassWord { get; set; }

        [NotMapped]
        [Required]
        [System.ComponentModel.DataAnnotations.Compare("PassWord")]

        public string ConfirmPassword { get; set; }

        public string Email { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> WorkStatus { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    }
}
